# must be unique in a given SonarQube Server instance
sonar.projectKey=shpcrt
sonar.projectName=Shopping Cart


# --- optional properties ---
sonar.sources=src/main
sonar.tests=src/test/java
sonar.coverage.exclusions=**/controller/**, **/view/**, **/exception/**
sonar.java.binaries=target/classes
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=$SONAR_TOKEN

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8